#!/bin/sh
export POSIXLY_CORRECT=yes
export LC_NUMERIC=en_US.UTF-8

########    USAGE    ########    
usage() {
    printf "USAGE:  tradelog [-h|--help] [FILTERS] [COMMAND] [LOG [LOG2 [...]]
            FILTERS:
                -a DATETIME     Records with DATE after DATETIME
                -b DATETIME     Records with DATE before DATETIME
                -t TICKER       Records with TICKER
                -w WIDTH        Set WIDTH of longest line

            COMMAND:
                list-tick       Prints list of TICKERs
                profit          Prints profit from closed positions (suma SELL - suma BUY)
                pos             Prints list of values of currently held positions in descending order 
                last-price      Prints last known price of TICKER 
                hist-ord        Prints histogram of the number of transactions according to TICKER 
                graph-pos       Prints list of values of held positions according to TICKER\n"
}

# FILTERS
AFTER_TIME_FILTER=""; BEFORE_TIME_FILTER="9999-99-99 99:99:99"; TICKS=""; WIDTH=""
# COMMAND
COMMAND=""
# FILE
INPUT=""
# SCRIPT OUTPUT
OUTPUT=""

while [ $# -gt 0 ]; do
    case "$1" in
    # FILTER 
    -a) if [ "$2" \> "$AFTER_TIME_FILTER" ]; then AFTER_TIME_FILTER=$2; fi; shift 2;;
    -b) if [ "$2" \< "$BEFORE_TIME_FILTER" ]; then BEFORE_TIME_FILTER=$2; fi; shift 2;;
    -t) if [ -z "$TICKS" ]; then TICKS="$2"; else TICKS="$TICKS\|$2"; fi; shift 2;;
    -w) WIDTH="$2"; shift 2;;

    # COMMAND
    list-tick | profit | pos | last-price | hist-ord | graph-pos) 
    if [ -z "$COMMAND" ]; then COMMAND="$1"; else printf "Called with more than one command.\n"; usage; exit 1; fi; shift 1 ;;

    # USAGE
    -h | --help) usage; exit 0;;
    # FILES
    *.log) INPUT="$INPUT\n$( cat $1 )"; shift 1;;
    *.gz) INPUT="$INPUT\n$( gzip -d -c $1 )"; shift 1;;
    
    # OTHER
    *) echo "Unavailable choice: '$1' - check input."; usage; exit 1;;
    esac
done

########    FILTERS    ########
TICKER_FILTER="grep '^.*;\($TICKS\);'"
DATETIME_FILTER="awk -F ';' '{ if ("\"$AFTER_TIME_FILTER"\"<\$1 && "\"$BEFORE_TIME_FILTER"\">"\$1") print }'"
if [ -z "$TICKS" ]; then    
    FILTERED_DATA='echo "$INPUT" | eval "$DATETIME_FILTER | sort"'
    else 
    FILTERED_DATA='echo "$INPUT" | eval "$TICKER_FILTER" | eval "$DATETIME_FILTER | sort"'
fi

########    COMMAND    ########
case $COMMAND in
    #print all tickers alphabetickly ordered
    list-tick) eval "$FILTERED_DATA" | sort -u -s -t ';' -k 2,2 | awk -F ';' '{print $2}' ;;

    #sell - buy
    profit) eval "$FILTERED_DATA" | sort -s -t ';' -k 2,3 ;;# here i skončit| awk 'FNR>1{for(i=3;i<=NF;i++){sum+=$i};if(sum>100){print sum > "out_file"};sum=""}' ;;##| awk -F ';' '{ if ($3=="buy") {array[$2$3]+=$4;} else {array[$2$3]-=$4;} print array[$2$3]}';; 

    pos) eval "$FILTERED_DATA" ;;

    last-price) eval "$FILTERED_DATA" ;;

    hist-ord) eval "$FILTERED_DATA" ;;

    graph-pos) eval "$FILTERED_DATA" ;;
esac



# DEBUG :)
: '
echo "AFTER_TIME_FILTER: $AFTER_TIME_FILTER"
echo "BEFORE_TIME_FILTER: $BEFORE_TIME_FILTER"
echo "TICKS: $TICKS"
echo "WIDTH: $WIDTH"
echo "COMMAND: $COMMAND"
'